version: "2"
services:
    db:
       image: mysql:5
       container_name: website-nir_db
       environment:
          MYSQL_DATABASE: dataname
          MYSQL_ROOT_PASSWORD: 123456
       volumes:
         - /srv/db:/var/lib/mysql
         - ./db/mysql:/etc/mysql
       restart: always
       ports:
         - "3333:3306" # 将3306映射到3333, 供其他容器使用
    web:
       build: .
       container_name: website-nir_web
       volumes:
       - .:/usr/src/app
       - ./logs:/tmp
       links:
           - db
       command: sh setup.sh
       depends_on:
       - db
       restart: always

    nginx:
       build: ./nginx
       container_name: website-nir_nginx
       ports:
       - "443:443"
       volumes:
       - ./static:/usr/share/nginx/html/static
       - ./media:/usr/share/nginx/html/media
       links:
       - web
       depends_on:
       - web
       restart: always
