version: "3"
services:
    db:
       image: mysql:5
       environment:
          MYSQL_DATABASE: dataname
          MYSQL_ROOT_PASSWORD: 123456
       volumes:
         - /srv/db:/var/lib/mysql
       restart: always
       ports:
         - "3306:3306"
    web:
       build: .
       volumes:
       - .:/usr/src/app
       - ./logs:/tmp
       links:
           - db
       command: sh setup.sh
       depends_on:
       - db
       restart: always

    nginx:
       build: ./nginx
       ports:
       - "81:80"
       volumes:
       - ./static:/usr/share/nginx/html/static
       - ./media:/usr/share/nginx/html/media
       links:
       - web
       depends_on:
       - web
       restart: always
